### ISSUE TITLE
Navigation - add active hover on "Real Time" to indicate to the user the page they are on

### ISSUE THREAD

**Issue by ngrad** [sunlightlabs/read_FEC#100]

**Comment by jsfenfen** [comment]
Closed in a98f995b2d9700eb1b89d8267dcd59d3c2ed73f3

**Comment by jsfenfen** [comment]
Hmm, so I used the CSS that FARA uses, but it's not quite right--the highlighted box is slightly bigger. Assuming this isn't the desired behavior, this should be fixed on FARA too.

**Comment by boblannon** [comment]
sorry, what's the status, then? the hover state that indicates where the user is seems to be set on the `li` tag, while the normal hover behavior happens on the `a` tag.  it's a bit ugly because they're different sizes:

![screenshot from 2015-01-26 11 16 26](https://cloud.githubusercontent.com/assets/1092694/5902970/de239202-a54c-11e4-98b4-ef354e591683.png)

**Comment by ngrad** [comment]
Jacob played with it last week and got the hover to stay on, I said I'd play with the css to get it just right but need to get the site up and running on my machine

**Comment by apendleton** [comment]
It's not clear to me how this happened. There are styles for all of this in the dryrub stylesheet, and they're all used on regular IE without this issue.

**Comment by boblannon** [comment]
Okay.  @ngrad, can you open an issue about setting up your machine and assign me to it?

**Comment by boblannon** [comment]
(it can be in the design repo, if that's more appropriate)
